---

binary_sensor:
  online_status:
    _key: status
    device_class: power
    payload_on: 'ONLINE'

sensor:
  # (e.g. online)
  status:
    icon: mdi:information-outline

  # Battery voltage as supplied by the UPS. (e.g. 27.3 volts)
  battery_voltage:
    _key: battv
    state_class: measurement
    device_class: voltage
    unit_of_measurement: 'V'
#    icon: mdi:flash

  # The nominal battery voltage. (e.g. 24.0 volts)
  battery_nominal_voltage:
    _key: nombattv
    entity_category: diagnostic
    device_class: voltage
    unit_of_measurement: 'V'
#    icon: mdi:flash

  # The percentage charge on the batteries. (e.g. 100.0 percent)
  battery:
    _key: bcharge
    state_class: measurement
    device_class: battery
    unit_of_measurement: '%'
#    icon: mdi:battery

  # If the battery charge percentage (BCHARGE) drops below this value, apcupsd will shutdown your system. (e.g. 5 percent)
  battery_shutdown:
    _key: mbattchg
    entity_category: diagnostic
    device_class: battery
    unit_of_measurement: '%'
    icon: mdi:battery-alert

  # Total (cumulative) time on batteries in seconds since apcupsd startup. (e.g. 0 seconds)
  total_time_on_battery:
    _key: cumonbatt
    entity_category: diagnostic
    state_class: measurement
    unit_of_measurement: 'Seconds'
    icon: mdi:timer-outline

  # The line voltage below which the UPS will switch to batteries. (e.g. 176.0 volts)
  transfer_low:
    _key: lotrans
    entity_category: diagnostic
    device_class: voltage
    unit_of_measurement: 'V'
#    icon: mdi:flash

  # The line voltage above which the UPS will switch to batteries. (e.g. 288.0 volts)
  transfer_high:
    _key: hitrans
    entity_category: diagnostic
    device_class: voltage
    unit_of_measurement: 'V'
#    icon: mdi:flash

  # The current line voltage as returned by the UPS. (e.g. 232.0 volts)
  input_voltage:
    _key: linev
    state_class: measurement
    device_class: voltage
    unit_of_measurement: 'V'
#    icon: mdi:flash

  # The input voltage that the UPS is configured to expect. (e.g. 230 volts)
  nominal_input_voltage:
    _key: nominv
    entity_category: diagnostic
    device_class: voltage
    unit_of_measurement: 'V'
#    icon: mdi:flash

  # The remaining runtime left on batteries as estimated by the UPS. (e.g. 40.9 minutes)
  time_left:
    _key: timeleft
    state_class: measurement
    unit_of_measurement: 'Minutes'
    icon: mdi:clock-alert

  # apcupsd will shutdown your system if the remaining runtime equals or is below this point. (e.g. 3 minutes)
  shutdown_time:
    _key: mintimel
    entity_category: diagnostic
    unit_of_measurement: 'Minutes'
    icon: mdi:timer-outline

  # The percentage of load capacity as estimated by the UPS. (e.g. 8.0 percent)
  load:
    _key: loadpct
    state_class: measurement
    unit_of_measurement: '%'
    icon: mdi:gauge

  # Current power usage in watts
  power:
    state_class: measurement
    device_class: power
    unit_of_measurement: 'W'

  # The maximum power in Watts that the UPS is designed to supply.
  nominal_power:
    _key: nompower
    entity_category: diagnostic
    device_class: power
    unit_of_measurement: 'W'

  # The reason for the last transfer to batteries.
  last_transfer:
    _key: lastxfer
    entity_category: diagnostic
    icon: mdi:transfer

  # The results of the last self test
  last_self_test:
    _key: selftest
    entity_category: diagnostic
    icon: mdi:calendar-clock

  # The number of transfers to batteries since apcupsd startup. (e.g. 0)
  transfer_count:
    _key: numxfers
    entity_category: diagnostic
    unit_of_measurement: 'x'
    icon: mdi:counter

  # The sensitivity level of the UPS to line voltage fluctuations. (e.g. high)
  sensitivity:
    _key: sense
    entity_category: diagnostic
    icon: mdi:information-outline
